// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"ItemBook","status":true,"description":"アイテム図鑑です。アイテムの詳細なステータスを表示します。","parameters":{"Unknown Data":"？？？？？？","Price Text":"価格","Equip Text":"装備","Type Text":"タイプ"}},
{"name":"EnemyBook","status":true,"description":"モンスター図鑑です。敵キャラの詳細なステータスを表示します。","parameters":{"Unknown Data":"？？？？？？"}},
{"name":"AutoBattle","status":true,"description":"ver1.03/戦闘中にキー入力でオートバトルを開始できるようにします。また、オートバトル中は高速化します。","parameters":{"Invalidate Auto Battle Switch":"11","Show X":"496","Show Y":"395","Auto Battle Speed":"4","Show Window":"true","Auto Battle Use Skill":"false","Window Hide Switch":"12","Auto Battle Key":"shift","Auto Battle Usable Message":"現在オートバトル中 _keyで解除","Auto Battle Message":"_keyでオートバトル開始"}},
{"name":"SlotMachine","status":true,"description":"Slot Machine scene","parameters":{"Variable ID":"11","Help Text":"カーソルキーの上でベット、カーソルキーの下でスタート","Won Text":"おめでとうございます！Win Coin枚獲得です！","Lost Text":"残念でした。","Replay Text":"もう一度やりますか？","Coin Full Text":"コイン枚数が制限に達しました。","Bet Text":"ベット","Spin Text":"スピン","Yes Text":"はい","No Text":"いいえ"}},
{"name":"SceneFormation","status":true,"description":"ver1.09/並び替えシーンを追加します。","parameters":{"Stand Members Size":"8","Max Battle Members Size":"4","Use Menu Formation Scene":"true","Formation Scene Battle Name":"戦闘メンバー","Formation Scene Stand Name":"待機メンバー","Use Battle Formation Switch ID":"20","Battle Command Formation":"Formation","Status Window Font Size":"24","Status Block Width":"372"}},
{"name":"Torigoya_ReplaceDeadMemberPlus","status":true,"description":"戦闘不能アクター自動入れ替えさんPlus","parameters":{"■ 基本設定":"","Save sort order":"ON","Disable switch ID":"0","■ こだわり設定":"","Can replace leader":"ON","Wait: Dead":"15","Wait: Replace":"30"}}
];
